# Generated by Django 6.0.4 on 2026-04-15 15:30

import django.db.models.deletion
import django.utils.timezone
import zenspendbackend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenspendbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(default=zenspendbackend.models.default_notification_preferences),
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_connection_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('action_required', 'Action Required'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=30)),
                ('institution_name', models.CharField(blank=True, max_length=120)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_connections',
            },
        ),
        migrations.CreateModel(
            name='ExternalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_transaction_id', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zenspendbackend.bankaccount')),
                ('bank_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transactions', to='zenspendbackend.bankconnection')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_reference', to='zenspendbackend.transaction')),
            ],
            options={
                'db_table': 'external_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['provider', 'status'], name='bank_connec_provide_a28764_idx'),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['-updated_at'], name='bank_connec_updated_788850_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankconnection',
            unique_together={('user', 'provider', 'external_connection_id')},
        ),
        migrations.AddIndex(
            model_name='externaltransaction',
            index=models.Index(fields=['-updated_at'], name='external_tr_updated_7defca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externaltransaction',
            unique_together={('bank_connection', 'external_transaction_id')},
        ),
    ]
