# Generated by Django 6.0.4 on 2026-04-16 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenspendbackend', '0003_user_user_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'households',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('parent', 'Parent'), ('partner', 'Partner'), ('child', 'Child')], default='child', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='zenspendbackend.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'household_members',
            },
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['owner', '-updated_at'], name='households_owner_i_e317c8_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['household', 'is_active'], name='household_m_househo_9e2180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='householdmember',
            unique_together={('household', 'user')},
        ),
    ]
