# Generated by Django 6.0.4 on 2026-04-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenspendbackend', '0004_household_householdmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedbudget',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_budgets', to='zenspendbackend.household'),
        ),
    ]
