# Generated by Django 6.0.4 on 2026-06-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenspendbackend', '0005_sharedbudget_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
