# Generated by Django 6.0.4 on 2026-06-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenspendbackend', '0006_userpreference_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
